=== pear/pear-core/PEAR/PackageFile/PHP5/package-1.0.xsd
<?xml version="1.0"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Greg Beaver (The Chiara String Quartet) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xs:element name="package">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="name"/>
    <xs:element ref="summary"/>
    <xs:element ref="description"/>
    <xs:element ref="license" minOccurs="0"/>
    <xs:element ref="maintainers"/>
    <xs:element ref="release"/>
    <xs:element ref="changelog" minOccurs="0"/>
   </xs:sequence>
   <xs:attribute name="type" default="empty">
    <xs:simpleType>
     <xs:restriction base="xs:string">
      <xs:enumeration value="source"/>
      <xs:enumeration value="binary"/>
      <xs:enumeration value="empty"/>
     </xs:restriction>
    </xs:simpleType>
   </xs:attribute>
   <xs:attribute name="version" type="xs:string" use="required"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="name" type="xs:string"/>
 <xs:element name="summary" type="xs:string"/>
 <xs:element name="description" type="xs:string"/>
 <xs:element name="license" type="xs:string"/>
 <xs:element name="maintainers">
  <xs:complexType>
   <xs:sequence maxOccurs="unbounded">
    <xs:element ref="maintainer"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name="maintainer">
  <xs:complexType>
   <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element ref="user"/>
    <xs:element ref="role"/>
    <xs:element ref="name"/>
    <xs:element ref="email"/>
   </xs:choice>
  </xs:complexType>
 </xs:element>
 <xs:element name="user" type="xs:string"/>
 <xs:element name="role" type="xs:string"/>
 <xs:element name="email" type="xs:string"/>
 <xs:element name="changelog">
  <xs:complexType>
   <xs:sequence minOccurs="0" maxOccurs="unbounded">
    <xs:element name="release" type="changelogrelease"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name="release">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="version"/>
    <xs:element ref="date"/>
    <xs:element ref="license"/>
    <xs:element ref="state"/>
    <xs:element ref="notes"/>
    <xs:element ref="warnings" minOccurs="0"/>
    <xs:element ref="provides" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element ref="deps" minOccurs="0"/>
    <xs:element ref="configureoptions" minOccurs="0"/>
    <xs:element ref="filelist"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name="version" type="xs:string"/>
 <xs:element name="state" type="xs:string"/>
 <xs:element name="date" type="xs:string"/>
 <xs:element name="notes" type="xs:string"/>
 <xs:element name="provides">
  <xs:complexType>
   <xs:attribute name="type" use="required">
    <xs:simpleType>
     <xs:restriction base="xs:string">
      <xs:enumeration value="ext"/>
      <xs:enumeration value="prog"/>
      <xs:enumeration value="class"/>
      <xs:enumeration value="function"/>
      <xs:enumeration value="feature"/>
      <xs:enumeration value="api"/>
     </xs:restriction>
    </xs:simpleType>
   </xs:attribute>
   <xs:attribute name="name" type="xs:string" use="required"/>
   <xs:attribute name="extends" type="xs:string"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="filelist">
  <xs:complexType>
   <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element ref="dir"/>
    <xs:element ref="file"/>
    <xs:element ref="libfile"/>
   </xs:choice>
  </xs:complexType>
 </xs:element>
 <xs:element name="dir">
  <xs:complexType>
   <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element ref="dir"/>
    <xs:element ref="file"/>
    <xs:element ref="libfile"/>
   </xs:choice>
   <xs:attribute name="name" type="xs:string" use="required"/>
   <xs:attribute name="baseinstalldir" type="xs:string"/>
   <xs:attribute name="role">
    <xs:simpleType>
     <xs:restriction base="xs:string">
      <xs:enumeration value="php"/>
      <xs:enumeration value="ext"/>
      <xs:enumeration value="test"/>
      <xs:enumeration value="doc"/>
      <xs:enumeration value="data"/>
      <xs:enumeration value="script"/>
      <xs:enumeration value="src"/>
     </xs:restriction>
    </xs:simpleType>
   </xs:attribute>
  </xs:complexType>
 </xs:element>
 <xs:element name="file">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="replace" minOccurs="0" maxOccurs="unbounded"/>
   </xs:sequence>
   <xs:attribute name="role" default="php">
    <xs:simpleType>
     <xs:restriction base="xs:string">
      <xs:enumeration value="php"/>
      <xs:enumeration value="ext"/>
      <xs:enumeration value="test"/>
      <xs:enumeration value="doc"/>
      <xs:enumeration value="data"/>
      <xs:enumeration value="script"/>
      <xs:enumeration value="src"/>
     </xs:restriction>
    </xs:simpleType>
   </xs:attribute>
   <xs:attribute name="debug" default="na">
    <xs:simpleType>
     <xs:restriction base="xs:string">
      <xs:enumeration value="na"/>
      <xs:enumeration value="on"/>
      <xs:enumeration value="off"/>
     </xs:restriction>
    </xs:simpleType>
   </xs:attribute>
   <xs:attribute name="threaded" default="na">
    <xs:simpleType>
     <xs:restriction base="xs:string">
      <xs:enumeration value="na"/>
      <xs:enumeration value="on"/>
      <xs:enumeration value="off"/>
     </xs:restriction>
    </xs:simpleType>
   </xs:attribute>
   <xs:attribute name="format" type="xs:string"/>
   <xs:attribute name="baseinstalldir" type="xs:string"/>
   <xs:attribute name="name" type="xs:string" use="required"/>
   <xs:attribute name="install-as" type="xs:string"/>
   <xs:attribute name="platform" type="xs:string"/>
   <xs:attribute name="md5sum" type="xs:string"/>
  </xs:complexType>
 </xs:element>
 <xs:element name="libfile">
  <xs:complexType>
   <xs:choice minOccurs="0" maxOccurs="unbounded">
    <xs:element ref="libname"/>
    <xs:element ref="sources"/>
    <xs:element ref="includes"/>
    <xs:element ref="libadd"/>
   </xs:choice>
  </xs:complexType>
 </xs:element>
 <xs:element name="libname" type="xs:string"/>
 <xs:element name="sources" type="xs:string"/>
 <xs:element name="includes" type="xs:string"/>
 <xs:element name="libadd" type="xs:string"/>
 <xs:element name="deps">
  <xs:complexType>
   <xs:sequence minOccurs="0" maxOccurs="unbounded">
    <xs:element ref="dep"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name="dep">
  <xs:complexType>
   <xs:simpleContent>
    <xs:extension base="xs:string">
     <xs:attribute name="type" use="required">
      <xs:simpleType>
       <xs:restriction base="xs:string">
        <xs:enumeration value="pkg"/>
        <xs:enumeration value="ext"/>
        <xs:enumeration value="php"/>
        <xs:enumeration value="prog"/>
        <xs:enumeration value="ldlib"/>
        <xs:enumeration value="ltlib"/>
        <xs:enumeration value="os"/>
        <xs:enumeration value="websrv"/>
        <xs:enumeration value="sapi"/>
       </xs:restriction>
      </xs:simpleType>
     </xs:attribute>
     <xs:attribute name="rel">
      <xs:simpleType>
       <xs:restriction base="xs:string">
        <xs:enumeration value="has"/>
        <xs:enumeration value="eq"/>
        <xs:enumeration value="lt"/>
        <xs:enumeration value="le"/>
        <xs:enumeration value="gt"/>
        <xs:enumeration value="ge"/>
       </xs:restriction>
      </xs:simpleType>
     </xs:attribute>
     <xs:attribute name="version" type="xs:string"/>
     <xs:attribute name="optional" default="no">
      <xs:simpleType>
       <xs:restriction base="xs:string">
        <xs:enumeration value="yes"/>
        <xs:enumeration value="no"/>
       </xs:restriction>
      </xs:simpleType>
     </xs:attribute>
    </xs:extension>
   </xs:simpleContent>
  </xs:complexType>
 </xs:element>
 <xs:element name="replace">
  <xs:complexType>
   <xs:attribute name="from" type="xs:string" use="required"/>
   <xs:attribute name="to" type="xs:string" use="required"/>
   <xs:attribute name="type" use="required">
    <xs:simpleType>
     <xs:restriction base="xs:string">
      <xs:enumeration value="package-info"/>
      <xs:enumeration value="pear-config"/>
      <xs:enumeration value="php-const"/>
     </xs:restriction>
    </xs:simpleType>
   </xs:attribute>
  </xs:complexType>
 </xs:element>
 <xs:complexType name="changelogrelease">
  <xs:sequence>
   <xs:element ref="version"/>
   <xs:element ref="date"/>
   <xs:element ref="license"/>
   <xs:element ref="state"/>
   <xs:element ref="notes"/>
  </xs:sequence>
 </xs:complexType>
 <xs:element name="warnings" type="xs:string"/>
 <xs:element name="configureoptions">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="configureoption" maxOccurs="unbounded"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name="configureoption">
  <xs:complexType>
   <xs:attribute name="name" type="xs:string" use="required"/>
   <xs:attribute name="default" type="xs:string"/>
   <xs:attribute name="prompt" type="xs:string" use="required"/>
  </xs:complexType>
 </xs:element>
</xs:schema>

=== pear/pear-core/package-PEAR.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--DOCTYPE package SYSTEM "http://pear.php.net/dtd/package-1.0"-->
<package version="1.0" xmlns="http://pear.php.net/dtd/package-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pear.php.net/dtd/package-1.0
http://pear.php.net/dtd/package-1.0.xsd">
 <name>PEAR</name>
 <summary>PEAR Base System</summary>
 <description>The PEAR package contains:
 * the PEAR installer, for creating, distributing
   and installing packages
 * the PEAR_Exception PHP5 error handling mechanism
 * the PEAR_ErrorStack advanced error handling mechanism
 * the PEAR_Error error handling mechanism
 * the OS_Guess class for retrieving info about the OS
   where PHP is running on
 * the System class for quick handling of common operations
   with files and directories
 * the PEAR base class

  Features in a nutshell:
  * full support for channels
  * pre-download dependency validation
  * new package.xml 2.0 format allows tremendous flexibility while maintaining BC
  * support for optional dependency groups and limited support for sub-packaging
  * robust dependency support
  * full dependency validation on uninstall
  * remote install for hosts with only ftp access - no more problems with
    restricted host installation
  * full support for mirroring
  * support for bundling several packages into a single tarball
  * support for static dependencies on a url-based package
  * support for custom file roles and installation tasks
 </description>
 <maintainers>
  <maintainer>
   <user>cellog</user>
   <role>lead</role>
   <name>Greg Beaver</name>
   <email>cellog@php.net</email>
  </maintainer>
  <maintainer>
   <user>pajoye</user>
   <role>lead</role>
   <name>Pierre-Alain Joye</name>
   <email>pierre@php.net</email>
  </maintainer>
  <maintainer>
   <user>ssb</user>
   <role>lead</role>
   <name>Stig Bakken</name>
   <email>stig@php.net</email>
  </maintainer>
  <maintainer>
   <user>cox</user>
   <role>lead</role>
   <name>Tomas V.V.Cox</name>
   <email>cox@idecnet.com</email>
  </maintainer>
  <maintainer>
   <user>dufuz</user>
   <role>lead</role>
   <name>Helgi Thormar</name>
   <email>dufuz@php.net</email>
  </maintainer>
  <maintainer>
   <user>tias</user>
   <role>developer</role>
   <name>Tias Guns</name>
   <email>tias@php.net</email>
  </maintainer>
  <maintainer>
   <user>timj</user>
   <role>helper</role>
   <name>Tim Jackson</name>
   <email>timj@php.net</email>
  </maintainer>
  <maintainer>
   <user>toggg</user>
   <role>helper</role>
   <name>Bertrand Gugger</name>
   <email>toggg@php.net</email>
  </maintainer>
  <maintainer>
   <user>mj</user>
   <role>helper</role>
   <name>Martin Jansen</name>
   <email>mj@php.net</email>
  </maintainer>
 </maintainers>
 <release>
  <version>1.10.0beta1</version>
  <date>2010-05-26</date>
  <license>New BSD License</license>
  <state>stable</state>
 <notes>
  PEAR_Exception has moved into it's own package so people can start putting dependency on PEAR_Exception
  instead of depending on PEAR when the Exception class is the only thing required.

  Features:
  * A configure parameter can now be passed to install / upgrade for pecl such as
    pecl install --with-option=dir memcached
    This allows for customized setups while still having the benefit of using the pear
    installer.
    (pear will not remember the configure params for the next upgrade)
 </notes>
  <provides type="class" name="OS_Guess"/>
  <provides type="class" name="System"/>
  <deps>
   <dep type="php" rel="ge" version="4.4.0"/>
   <dep type="pkg" rel="ge" version="1.3.3">PEAR</dep>
   <dep type="pkg" rel="ge" version="1.3.7">Archive_Tar</dep>
   <dep type="pkg" rel="ge" version="1.3.0">Console_Getopt</dep>
   <dep type="pkg" rel="ge" version="1.0.4">Structures_Graph</dep>
   <dep type="pkg" rel="ge" version="1.0.0beta1" optional="yes">PEAR_Exception</dep>
   <dep type="pkg" rel="ge" version="0.5.0" optional="yes">PEAR_Frontend_Web</dep>
   <dep type="pkg" rel="ge" version="0.4.0" optional="yes">PEAR_Frontend_Gtk</dep>
   <dep type="ext" rel="has">xml</dep>
   <dep type="ext" rel="has">pcre</dep>
  </deps>
  <filelist>
   <dir name="OS">
    <file role="php" name="Guess.php">
     <replace from="@package_version@" to="version" type="package-info"/>
    </file>
   </dir>
   <dir name="PEAR">
    <dir name="ChannelFile">
     <file name="Parser.php" role="php">
      <replace from="@package_version@" to="version" type="package-info"/>
     </file>
    </dir>
    <dir name="Command">
     <file role="php" name="Auth.xml"/>
     <file role="php" name="Auth.php">
      <replace from="@package_version@" to="version" type="package-info"/>
     </file>
     <file role="php" name="Build.xml"/>
     <file role="php" name="Build.php">
      <replace from="@package_version@" to="version" type="package-info"/>
     </file>
     <file role="php" name="Channels.xml"/>
     <file role="php" name="Channels.php">
      <replace from="@package_version@" to="version" type="package-info"/>
     </file>
     <file role="php" name="Common.php">
      <replace from="@package_version@" to="version" type="package-info"/>
     </file>
     <file role="php" name="Config.xml"/>
     <file role="php" name="Config.php">
      <replace from="@package_version@" to="version" type="package-info"/>
     </file>
     <file role="php" name="Install.xml"/>
     <file role="php" name="Install.php">
      <replace from="@package_version@" to="version" type="package-info"/>
     </file>
     <file role="php" name="Package.xml"/>
     <file role="php" name="Package.php">
      <replace from="@DATA-DIR@" to="data_dir" type="pear-config"/>
      <replace from="@package_version@" to="version" type="package-info"/>
     </file>
     <file role="php" name="Pickle.xml"/>
     <file role="php" name="Pickle.php">
      <replace from="@package_version@" to="version" type="package-info"/>
     </file>
     <file role="php" name="Registry.xml"/>
     <file role="php" name="Registry.php">
      <replace from="@package_version@" to="version" type="package-info"/>
     </file>
     <file role="php" name="Remote.xml"/>
     <file role="php" name="Remote.php">
      <replace from="@package_version@" to="version" type="package-info"/>
     </file>
     <file role="php" name="Mirror.xml"/>
     <file role="php" name="Mirror.php">
      <replace from="@package_version@" to="version" type="package-info"/>
     </file>
     <file role="php" name="Test.xml"/>
     <file role="php" name="Test.php">
      <replace from="@package_version@" to="version" type="package-info"/>
     </file>
    </dir>
    <dir name="Downloader">
     <file role="php" name="Package.php">
      <replace from="@PEAR-VER@" to="version" type="package-info"/>
     </file>
    </dir>
    <dir name="Frontend">
     <file role="php" name="CLI.php">
      <replace from="@package_version@" to="version" type="package-info"/>
     </file>
    </dir>
    <dir name="Installer">
     <dir name="Role">
      <file role="php" name="Common.php">
       <replace from="@package_version@" to="version" type="package-info"/>
      </file>
      <file role="php" name="Cfg.xml"/>
      <file role="php" name="Cfg.php">
       <replace from="@package_version@" to="version" type="package-info"/>
      </file>
      <file role="php" name="Data.xml"/>
      <file role="php" name="Data.php">
       <replace from="@package_version@" to="version" type="package-info"/>
      </file>
      <file role="php" name="Doc.xml"/>
      <file role="php" name="Doc.php">
       <replace from="@package_version@" to="version" type="package-info"/>
      </file>
      <file role="php" name="Ext.xml"/>
      <file role="php" name="Ext.php">
       <replace from="@package_version@" to="version" type="package-info"/>
      </file>
      <file role="php" name="Php.xml"/>
      <file role="php" name="Php.php">
       <replace from="@package_version@" to="version" type="package-info"/>
      </file>
      <file role="php" name="Script.xml"/>
      <file role="php" name="Script.php">
       <replace from="@package_version@" to="version" type="package-info"/>
      </file>
      <file role="php" name="Src.xml"/>
      <file role="php" name="Src.php">
       <replace from="@package_version@" to="version" type="package-info"/>
      </file>
      <file role="php" name="Test.xml"/>
      <file role="php" name="Test.php">
       <replace from="@package_version@" to="version" type="package-info"/>
      </file>
      <file role="php" name="Www.xml"/>
      <file role="php" name="Www.php">
       <replace from="@package_version@" to="version" type="package-info"/>
      </file>
     </dir>
     <file role="php" name="Role.php">
      <replace from="@package_version@" to="version" type="package-info"/>
     </file>
    </dir>
    <dir name="PackageFile">
     <dir name="Generator">
      <file role="php" name="v1.php">
       <replace from="@PEAR-VER@" to="version" type="package-info"/>
      </file>
      <file role="php" name="v2.php">
       <replace from="@PEAR-VER@" to="version" type="package-info"/>
      </file>
     </dir>
     <dir name="Parser">
      <file role="php" name="v1.php">
       <replace from="@package_version@" to="version" type="package-info"/>
      </file>
      <file role="php" name="v2.php">
       <replace from="@package_version@" to="version" type="package-info"/>
      </file>
     </dir>
     <dir name="v2">
      <file role="php" name="rw.php">
       <replace from="@package_version@" to="version" type="package-info"/>
      </file>
      <file role="php" name="Validator.php">
       <replace from="@package_version@" to="version" type="package-info"/>
      </file>
     </dir>
